trigger:
- '*'

variables:
  webRepository: 'web'
  tag: 'latest'
  #tag: '$(Build.BuildId)'

stages:
- stage: 'Build'
  displayName: 'Build and push'
  jobs:  
  - job: 'Build'
    displayName: 'Build job'
    pool:
      name: Default
    steps:
    - task: Docker@2
      displayName: 'Build and push the image to container registry'
      inputs:
        command: buildAndPush
        buildContext: $(Build.Repository.LocalPath)
        repository: $(webRepository)
        dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Dockerfile'
        containerRegistry: 'Docker Private Registry (registrystaging.stardekk.com)'
        tags: |
          $(tag)

- stage: 'Deploy'
  displayName: 'Deploy the container'
  dependsOn: Build
  jobs:
  - job: 'Deploy'
    displayName: 'Deploy job'
    continueOnError: true
    pool:
      name: Default
    variables:
    - group: Release
    steps:
    - task: SSH@0
      inputs: 
        sshEndpoint: 'SSH Service Connection'
        runOptions: inline
        inline: |
          containerID=$(/snap/bin/docker ps -a -q --filter ancestor=registrystaging.stardekk.com:443/web:latest --format="{{.ID}}")
          echo $containerID
          stopContainerID=$(/snap/bin/docker stop $containerID)
          /snap/bin/docker rm $stopContainerID
          /snap/bin/docker run -d -p 80:80 registrystaging.stardekk.com:443/web:latest
         #/snap/bin/docker rm $(/snap/bin/docker stop $(/snap/bin/docker ps -a -q --filter ancestor=registrystaging.stardekk.com:443/web:latest --format="{{.ID}}"))
           
    #set +e;
    #change this!